### PR TITLE
Add Sequence Ontology identifiers as supported featureTypes

### LINKED ISSUE #40: Add Sequence Ontology identifiers as supported featureTypes
E.g. here
https://github.com/bigdatagenomics/quinine/blob/master/quinine-core/src/main/scala/org/bdgenomics/quinine/metrics/rna/RNASeqAlignmentCounts.scala#L43

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #40

### CODE REVIEW

**Comment by heuermh** [comment]
The right way is to load the entire SO in as a graph and do graph queries or into a triple store and reason, since e.g. `primary_transcript` `is_a` `transcript`, and we should include those features when calculating overlaps.

But I don't believe we want to do it the right way, so I'm ok with the shortcut here.

**Comment by fnothaft** [comment]
"right way"

**Comment by fnothaft** [comment]
I was just realizing that I hadn't merged this, and wanted to come back to this. Mostly, I want to open a ticket in "the right place" before I merge this so that we don't lose track.

> we should include those features when calculating overlaps.

Can you give an example of how we'd use SO features in a query? Would we run an overlap join where we pre-filter on all things that our SO say are a transcript?

**Comment by fnothaft** [comment]
I'm not an ontologist, so IDGI, but I'd like to understand it because I would like to be friends with more ontologists. ;)

**Review by fnothaft — APPROVED** [review]

**Comment by fnothaft** [comment]
Merged! Thanks @heuermh!

**Pull request merged**
